<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:macro name="inertia_box" params="x y z mass">
      <mass value="${mass}" />
      <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
        izz="${0.0833333 * mass * (x*x + y*y)}" />
  </xacro:macro>
  
  <xacro:macro name="car_chassis" params="name parent xyz rpy">   
      
  <xacro:property name="plate_x"    value="0.26" />
  <xacro:property name="plate_y"    value="0.08" />
  <xacro:property name="plate_z"    value="0.02" />

    <!-- Chassis -->
    <joint name="${parent}_${name}_joint" type="fixed">
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <parent link="${parent}"/>
        <child link="${name}"/>
    </joint>
    <link name="${name}">
        <visual>
            <origin xyz="${plate_x/2} 0 -${plate_z}" rpy="0 0 0"/>
            <geometry>
                <box size="${plate_x} ${plate_y} ${plate_z}"/>
            </geometry>
            <material name="ChassisRed">
                <color rgba="0.851 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="${plate_x/2} 0 -${plate_z}" rpy="0 0 0"/>
            <geometry>
                <box size="${plate_x} ${plate_y} ${plate_z}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${plate_x/2} 0 -${plate_z}" />
            <xacro:inertia_box x="${plate_x}" y="${plate_y}"  z="${plate_z}" mass="0.01" />
        </inertial>
    </link>  
  </xacro:macro>

</robot>
